// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: genesis.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_genesis_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_genesis_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_genesis_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_genesis_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_genesis_2eproto;
namespace corepb {
class Genesis;
class GenesisDefaultTypeInternal;
extern GenesisDefaultTypeInternal _Genesis_default_instance_;
class GenesisConsensus;
class GenesisConsensusDefaultTypeInternal;
extern GenesisConsensusDefaultTypeInternal _GenesisConsensus_default_instance_;
class GenesisConsensusDpos;
class GenesisConsensusDposDefaultTypeInternal;
extern GenesisConsensusDposDefaultTypeInternal _GenesisConsensusDpos_default_instance_;
class GenesisMeta;
class GenesisMetaDefaultTypeInternal;
extern GenesisMetaDefaultTypeInternal _GenesisMeta_default_instance_;
class GenesisTokenDistribution;
class GenesisTokenDistributionDefaultTypeInternal;
extern GenesisTokenDistributionDefaultTypeInternal _GenesisTokenDistribution_default_instance_;
}  // namespace corepb
PROTOBUF_NAMESPACE_OPEN
template<> ::corepb::Genesis* Arena::CreateMaybeMessage<::corepb::Genesis>(Arena*);
template<> ::corepb::GenesisConsensus* Arena::CreateMaybeMessage<::corepb::GenesisConsensus>(Arena*);
template<> ::corepb::GenesisConsensusDpos* Arena::CreateMaybeMessage<::corepb::GenesisConsensusDpos>(Arena*);
template<> ::corepb::GenesisMeta* Arena::CreateMaybeMessage<::corepb::GenesisMeta>(Arena*);
template<> ::corepb::GenesisTokenDistribution* Arena::CreateMaybeMessage<::corepb::GenesisTokenDistribution>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace corepb {

// ===================================================================

class Genesis :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corepb.Genesis) */ {
 public:
  Genesis();
  virtual ~Genesis();

  Genesis(const Genesis& from);
  Genesis(Genesis&& from) noexcept
    : Genesis() {
    *this = ::std::move(from);
  }

  inline Genesis& operator=(const Genesis& from) {
    CopyFrom(from);
    return *this;
  }
  inline Genesis& operator=(Genesis&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Genesis& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Genesis* internal_default_instance() {
    return reinterpret_cast<const Genesis*>(
               &_Genesis_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Genesis& a, Genesis& b) {
    a.Swap(&b);
  }
  inline void Swap(Genesis* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Genesis* New() const final {
    return CreateMaybeMessage<Genesis>(nullptr);
  }

  Genesis* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Genesis>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Genesis& from);
  void MergeFrom(const Genesis& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Genesis* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corepb.Genesis";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_genesis_2eproto);
    return ::descriptor_table_genesis_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenDistributionFieldNumber = 3,
    kMetaFieldNumber = 1,
    kConsensusFieldNumber = 2,
  };
  // repeated .corepb.GenesisTokenDistribution token_distribution = 3;
  int token_distribution_size() const;
  private:
  int _internal_token_distribution_size() const;
  public:
  void clear_token_distribution();
  ::corepb::GenesisTokenDistribution* mutable_token_distribution(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::corepb::GenesisTokenDistribution >*
      mutable_token_distribution();
  private:
  const ::corepb::GenesisTokenDistribution& _internal_token_distribution(int index) const;
  ::corepb::GenesisTokenDistribution* _internal_add_token_distribution();
  public:
  const ::corepb::GenesisTokenDistribution& token_distribution(int index) const;
  ::corepb::GenesisTokenDistribution* add_token_distribution();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::corepb::GenesisTokenDistribution >&
      token_distribution() const;

  // .corepb.GenesisMeta meta = 1;
  bool has_meta() const;
  private:
  bool _internal_has_meta() const;
  public:
  void clear_meta();
  const ::corepb::GenesisMeta& meta() const;
  ::corepb::GenesisMeta* release_meta();
  ::corepb::GenesisMeta* mutable_meta();
  void set_allocated_meta(::corepb::GenesisMeta* meta);
  private:
  const ::corepb::GenesisMeta& _internal_meta() const;
  ::corepb::GenesisMeta* _internal_mutable_meta();
  public:

  // .corepb.GenesisConsensus consensus = 2;
  bool has_consensus() const;
  private:
  bool _internal_has_consensus() const;
  public:
  void clear_consensus();
  const ::corepb::GenesisConsensus& consensus() const;
  ::corepb::GenesisConsensus* release_consensus();
  ::corepb::GenesisConsensus* mutable_consensus();
  void set_allocated_consensus(::corepb::GenesisConsensus* consensus);
  private:
  const ::corepb::GenesisConsensus& _internal_consensus() const;
  ::corepb::GenesisConsensus* _internal_mutable_consensus();
  public:

  // @@protoc_insertion_point(class_scope:corepb.Genesis)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::corepb::GenesisTokenDistribution > token_distribution_;
  ::corepb::GenesisMeta* meta_;
  ::corepb::GenesisConsensus* consensus_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_genesis_2eproto;
};
// -------------------------------------------------------------------

class GenesisMeta :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corepb.GenesisMeta) */ {
 public:
  GenesisMeta();
  virtual ~GenesisMeta();

  GenesisMeta(const GenesisMeta& from);
  GenesisMeta(GenesisMeta&& from) noexcept
    : GenesisMeta() {
    *this = ::std::move(from);
  }

  inline GenesisMeta& operator=(const GenesisMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenesisMeta& operator=(GenesisMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GenesisMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenesisMeta* internal_default_instance() {
    return reinterpret_cast<const GenesisMeta*>(
               &_GenesisMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GenesisMeta& a, GenesisMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(GenesisMeta* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GenesisMeta* New() const final {
    return CreateMaybeMessage<GenesisMeta>(nullptr);
  }

  GenesisMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GenesisMeta>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GenesisMeta& from);
  void MergeFrom(const GenesisMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenesisMeta* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corepb.GenesisMeta";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_genesis_2eproto);
    return ::descriptor_table_genesis_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChainIdFieldNumber = 1,
  };
  // uint32 chain_id = 1;
  void clear_chain_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 chain_id() const;
  void set_chain_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_chain_id() const;
  void _internal_set_chain_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:corepb.GenesisMeta)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 chain_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_genesis_2eproto;
};
// -------------------------------------------------------------------

class GenesisConsensus :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corepb.GenesisConsensus) */ {
 public:
  GenesisConsensus();
  virtual ~GenesisConsensus();

  GenesisConsensus(const GenesisConsensus& from);
  GenesisConsensus(GenesisConsensus&& from) noexcept
    : GenesisConsensus() {
    *this = ::std::move(from);
  }

  inline GenesisConsensus& operator=(const GenesisConsensus& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenesisConsensus& operator=(GenesisConsensus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GenesisConsensus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenesisConsensus* internal_default_instance() {
    return reinterpret_cast<const GenesisConsensus*>(
               &_GenesisConsensus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GenesisConsensus& a, GenesisConsensus& b) {
    a.Swap(&b);
  }
  inline void Swap(GenesisConsensus* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GenesisConsensus* New() const final {
    return CreateMaybeMessage<GenesisConsensus>(nullptr);
  }

  GenesisConsensus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GenesisConsensus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GenesisConsensus& from);
  void MergeFrom(const GenesisConsensus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenesisConsensus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corepb.GenesisConsensus";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_genesis_2eproto);
    return ::descriptor_table_genesis_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDposFieldNumber = 1,
  };
  // .corepb.GenesisConsensusDpos dpos = 1;
  bool has_dpos() const;
  private:
  bool _internal_has_dpos() const;
  public:
  void clear_dpos();
  const ::corepb::GenesisConsensusDpos& dpos() const;
  ::corepb::GenesisConsensusDpos* release_dpos();
  ::corepb::GenesisConsensusDpos* mutable_dpos();
  void set_allocated_dpos(::corepb::GenesisConsensusDpos* dpos);
  private:
  const ::corepb::GenesisConsensusDpos& _internal_dpos() const;
  ::corepb::GenesisConsensusDpos* _internal_mutable_dpos();
  public:

  // @@protoc_insertion_point(class_scope:corepb.GenesisConsensus)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::corepb::GenesisConsensusDpos* dpos_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_genesis_2eproto;
};
// -------------------------------------------------------------------

class GenesisConsensusDpos :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corepb.GenesisConsensusDpos) */ {
 public:
  GenesisConsensusDpos();
  virtual ~GenesisConsensusDpos();

  GenesisConsensusDpos(const GenesisConsensusDpos& from);
  GenesisConsensusDpos(GenesisConsensusDpos&& from) noexcept
    : GenesisConsensusDpos() {
    *this = ::std::move(from);
  }

  inline GenesisConsensusDpos& operator=(const GenesisConsensusDpos& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenesisConsensusDpos& operator=(GenesisConsensusDpos&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GenesisConsensusDpos& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenesisConsensusDpos* internal_default_instance() {
    return reinterpret_cast<const GenesisConsensusDpos*>(
               &_GenesisConsensusDpos_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GenesisConsensusDpos& a, GenesisConsensusDpos& b) {
    a.Swap(&b);
  }
  inline void Swap(GenesisConsensusDpos* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GenesisConsensusDpos* New() const final {
    return CreateMaybeMessage<GenesisConsensusDpos>(nullptr);
  }

  GenesisConsensusDpos* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GenesisConsensusDpos>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GenesisConsensusDpos& from);
  void MergeFrom(const GenesisConsensusDpos& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenesisConsensusDpos* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corepb.GenesisConsensusDpos";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_genesis_2eproto);
    return ::descriptor_table_genesis_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDynastyFieldNumber = 1,
  };
  // repeated string dynasty = 1;
  int dynasty_size() const;
  private:
  int _internal_dynasty_size() const;
  public:
  void clear_dynasty();
  const std::string& dynasty(int index) const;
  std::string* mutable_dynasty(int index);
  void set_dynasty(int index, const std::string& value);
  void set_dynasty(int index, std::string&& value);
  void set_dynasty(int index, const char* value);
  void set_dynasty(int index, const char* value, size_t size);
  std::string* add_dynasty();
  void add_dynasty(const std::string& value);
  void add_dynasty(std::string&& value);
  void add_dynasty(const char* value);
  void add_dynasty(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& dynasty() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_dynasty();
  private:
  const std::string& _internal_dynasty(int index) const;
  std::string* _internal_add_dynasty();
  public:

  // @@protoc_insertion_point(class_scope:corepb.GenesisConsensusDpos)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> dynasty_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_genesis_2eproto;
};
// -------------------------------------------------------------------

class GenesisTokenDistribution :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corepb.GenesisTokenDistribution) */ {
 public:
  GenesisTokenDistribution();
  virtual ~GenesisTokenDistribution();

  GenesisTokenDistribution(const GenesisTokenDistribution& from);
  GenesisTokenDistribution(GenesisTokenDistribution&& from) noexcept
    : GenesisTokenDistribution() {
    *this = ::std::move(from);
  }

  inline GenesisTokenDistribution& operator=(const GenesisTokenDistribution& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenesisTokenDistribution& operator=(GenesisTokenDistribution&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GenesisTokenDistribution& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenesisTokenDistribution* internal_default_instance() {
    return reinterpret_cast<const GenesisTokenDistribution*>(
               &_GenesisTokenDistribution_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(GenesisTokenDistribution& a, GenesisTokenDistribution& b) {
    a.Swap(&b);
  }
  inline void Swap(GenesisTokenDistribution* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GenesisTokenDistribution* New() const final {
    return CreateMaybeMessage<GenesisTokenDistribution>(nullptr);
  }

  GenesisTokenDistribution* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GenesisTokenDistribution>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GenesisTokenDistribution& from);
  void MergeFrom(const GenesisTokenDistribution& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenesisTokenDistribution* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corepb.GenesisTokenDistribution";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_genesis_2eproto);
    return ::descriptor_table_genesis_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddressFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // string address = 1;
  void clear_address();
  const std::string& address() const;
  void set_address(const std::string& value);
  void set_address(std::string&& value);
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  std::string* mutable_address();
  std::string* release_address();
  void set_allocated_address(std::string* address);
  private:
  const std::string& _internal_address() const;
  void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // string value = 2;
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:corepb.GenesisTokenDistribution)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_genesis_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Genesis

// .corepb.GenesisMeta meta = 1;
inline bool Genesis::_internal_has_meta() const {
  return this != internal_default_instance() && meta_ != nullptr;
}
inline bool Genesis::has_meta() const {
  return _internal_has_meta();
}
inline void Genesis::clear_meta() {
  if (GetArenaNoVirtual() == nullptr && meta_ != nullptr) {
    delete meta_;
  }
  meta_ = nullptr;
}
inline const ::corepb::GenesisMeta& Genesis::_internal_meta() const {
  const ::corepb::GenesisMeta* p = meta_;
  return p != nullptr ? *p : *reinterpret_cast<const ::corepb::GenesisMeta*>(
      &::corepb::_GenesisMeta_default_instance_);
}
inline const ::corepb::GenesisMeta& Genesis::meta() const {
  // @@protoc_insertion_point(field_get:corepb.Genesis.meta)
  return _internal_meta();
}
inline ::corepb::GenesisMeta* Genesis::release_meta() {
  // @@protoc_insertion_point(field_release:corepb.Genesis.meta)
  
  ::corepb::GenesisMeta* temp = meta_;
  meta_ = nullptr;
  return temp;
}
inline ::corepb::GenesisMeta* Genesis::_internal_mutable_meta() {
  
  if (meta_ == nullptr) {
    auto* p = CreateMaybeMessage<::corepb::GenesisMeta>(GetArenaNoVirtual());
    meta_ = p;
  }
  return meta_;
}
inline ::corepb::GenesisMeta* Genesis::mutable_meta() {
  // @@protoc_insertion_point(field_mutable:corepb.Genesis.meta)
  return _internal_mutable_meta();
}
inline void Genesis::set_allocated_meta(::corepb::GenesisMeta* meta) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete meta_;
  }
  if (meta) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      meta = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, meta, submessage_arena);
    }
    
  } else {
    
  }
  meta_ = meta;
  // @@protoc_insertion_point(field_set_allocated:corepb.Genesis.meta)
}

// .corepb.GenesisConsensus consensus = 2;
inline bool Genesis::_internal_has_consensus() const {
  return this != internal_default_instance() && consensus_ != nullptr;
}
inline bool Genesis::has_consensus() const {
  return _internal_has_consensus();
}
inline void Genesis::clear_consensus() {
  if (GetArenaNoVirtual() == nullptr && consensus_ != nullptr) {
    delete consensus_;
  }
  consensus_ = nullptr;
}
inline const ::corepb::GenesisConsensus& Genesis::_internal_consensus() const {
  const ::corepb::GenesisConsensus* p = consensus_;
  return p != nullptr ? *p : *reinterpret_cast<const ::corepb::GenesisConsensus*>(
      &::corepb::_GenesisConsensus_default_instance_);
}
inline const ::corepb::GenesisConsensus& Genesis::consensus() const {
  // @@protoc_insertion_point(field_get:corepb.Genesis.consensus)
  return _internal_consensus();
}
inline ::corepb::GenesisConsensus* Genesis::release_consensus() {
  // @@protoc_insertion_point(field_release:corepb.Genesis.consensus)
  
  ::corepb::GenesisConsensus* temp = consensus_;
  consensus_ = nullptr;
  return temp;
}
inline ::corepb::GenesisConsensus* Genesis::_internal_mutable_consensus() {
  
  if (consensus_ == nullptr) {
    auto* p = CreateMaybeMessage<::corepb::GenesisConsensus>(GetArenaNoVirtual());
    consensus_ = p;
  }
  return consensus_;
}
inline ::corepb::GenesisConsensus* Genesis::mutable_consensus() {
  // @@protoc_insertion_point(field_mutable:corepb.Genesis.consensus)
  return _internal_mutable_consensus();
}
inline void Genesis::set_allocated_consensus(::corepb::GenesisConsensus* consensus) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete consensus_;
  }
  if (consensus) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      consensus = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, consensus, submessage_arena);
    }
    
  } else {
    
  }
  consensus_ = consensus;
  // @@protoc_insertion_point(field_set_allocated:corepb.Genesis.consensus)
}

// repeated .corepb.GenesisTokenDistribution token_distribution = 3;
inline int Genesis::_internal_token_distribution_size() const {
  return token_distribution_.size();
}
inline int Genesis::token_distribution_size() const {
  return _internal_token_distribution_size();
}
inline void Genesis::clear_token_distribution() {
  token_distribution_.Clear();
}
inline ::corepb::GenesisTokenDistribution* Genesis::mutable_token_distribution(int index) {
  // @@protoc_insertion_point(field_mutable:corepb.Genesis.token_distribution)
  return token_distribution_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::corepb::GenesisTokenDistribution >*
Genesis::mutable_token_distribution() {
  // @@protoc_insertion_point(field_mutable_list:corepb.Genesis.token_distribution)
  return &token_distribution_;
}
inline const ::corepb::GenesisTokenDistribution& Genesis::_internal_token_distribution(int index) const {
  return token_distribution_.Get(index);
}
inline const ::corepb::GenesisTokenDistribution& Genesis::token_distribution(int index) const {
  // @@protoc_insertion_point(field_get:corepb.Genesis.token_distribution)
  return _internal_token_distribution(index);
}
inline ::corepb::GenesisTokenDistribution* Genesis::_internal_add_token_distribution() {
  return token_distribution_.Add();
}
inline ::corepb::GenesisTokenDistribution* Genesis::add_token_distribution() {
  // @@protoc_insertion_point(field_add:corepb.Genesis.token_distribution)
  return _internal_add_token_distribution();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::corepb::GenesisTokenDistribution >&
Genesis::token_distribution() const {
  // @@protoc_insertion_point(field_list:corepb.Genesis.token_distribution)
  return token_distribution_;
}

// -------------------------------------------------------------------

// GenesisMeta

// uint32 chain_id = 1;
inline void GenesisMeta::clear_chain_id() {
  chain_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GenesisMeta::_internal_chain_id() const {
  return chain_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GenesisMeta::chain_id() const {
  // @@protoc_insertion_point(field_get:corepb.GenesisMeta.chain_id)
  return _internal_chain_id();
}
inline void GenesisMeta::_internal_set_chain_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  chain_id_ = value;
}
inline void GenesisMeta::set_chain_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_chain_id(value);
  // @@protoc_insertion_point(field_set:corepb.GenesisMeta.chain_id)
}

// -------------------------------------------------------------------

// GenesisConsensus

// .corepb.GenesisConsensusDpos dpos = 1;
inline bool GenesisConsensus::_internal_has_dpos() const {
  return this != internal_default_instance() && dpos_ != nullptr;
}
inline bool GenesisConsensus::has_dpos() const {
  return _internal_has_dpos();
}
inline void GenesisConsensus::clear_dpos() {
  if (GetArenaNoVirtual() == nullptr && dpos_ != nullptr) {
    delete dpos_;
  }
  dpos_ = nullptr;
}
inline const ::corepb::GenesisConsensusDpos& GenesisConsensus::_internal_dpos() const {
  const ::corepb::GenesisConsensusDpos* p = dpos_;
  return p != nullptr ? *p : *reinterpret_cast<const ::corepb::GenesisConsensusDpos*>(
      &::corepb::_GenesisConsensusDpos_default_instance_);
}
inline const ::corepb::GenesisConsensusDpos& GenesisConsensus::dpos() const {
  // @@protoc_insertion_point(field_get:corepb.GenesisConsensus.dpos)
  return _internal_dpos();
}
inline ::corepb::GenesisConsensusDpos* GenesisConsensus::release_dpos() {
  // @@protoc_insertion_point(field_release:corepb.GenesisConsensus.dpos)
  
  ::corepb::GenesisConsensusDpos* temp = dpos_;
  dpos_ = nullptr;
  return temp;
}
inline ::corepb::GenesisConsensusDpos* GenesisConsensus::_internal_mutable_dpos() {
  
  if (dpos_ == nullptr) {
    auto* p = CreateMaybeMessage<::corepb::GenesisConsensusDpos>(GetArenaNoVirtual());
    dpos_ = p;
  }
  return dpos_;
}
inline ::corepb::GenesisConsensusDpos* GenesisConsensus::mutable_dpos() {
  // @@protoc_insertion_point(field_mutable:corepb.GenesisConsensus.dpos)
  return _internal_mutable_dpos();
}
inline void GenesisConsensus::set_allocated_dpos(::corepb::GenesisConsensusDpos* dpos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete dpos_;
  }
  if (dpos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      dpos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, dpos, submessage_arena);
    }
    
  } else {
    
  }
  dpos_ = dpos;
  // @@protoc_insertion_point(field_set_allocated:corepb.GenesisConsensus.dpos)
}

// -------------------------------------------------------------------

// GenesisConsensusDpos

// repeated string dynasty = 1;
inline int GenesisConsensusDpos::_internal_dynasty_size() const {
  return dynasty_.size();
}
inline int GenesisConsensusDpos::dynasty_size() const {
  return _internal_dynasty_size();
}
inline void GenesisConsensusDpos::clear_dynasty() {
  dynasty_.Clear();
}
inline std::string* GenesisConsensusDpos::add_dynasty() {
  // @@protoc_insertion_point(field_add_mutable:corepb.GenesisConsensusDpos.dynasty)
  return _internal_add_dynasty();
}
inline const std::string& GenesisConsensusDpos::_internal_dynasty(int index) const {
  return dynasty_.Get(index);
}
inline const std::string& GenesisConsensusDpos::dynasty(int index) const {
  // @@protoc_insertion_point(field_get:corepb.GenesisConsensusDpos.dynasty)
  return _internal_dynasty(index);
}
inline std::string* GenesisConsensusDpos::mutable_dynasty(int index) {
  // @@protoc_insertion_point(field_mutable:corepb.GenesisConsensusDpos.dynasty)
  return dynasty_.Mutable(index);
}
inline void GenesisConsensusDpos::set_dynasty(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:corepb.GenesisConsensusDpos.dynasty)
  dynasty_.Mutable(index)->assign(value);
}
inline void GenesisConsensusDpos::set_dynasty(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:corepb.GenesisConsensusDpos.dynasty)
  dynasty_.Mutable(index)->assign(std::move(value));
}
inline void GenesisConsensusDpos::set_dynasty(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  dynasty_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:corepb.GenesisConsensusDpos.dynasty)
}
inline void GenesisConsensusDpos::set_dynasty(int index, const char* value, size_t size) {
  dynasty_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:corepb.GenesisConsensusDpos.dynasty)
}
inline std::string* GenesisConsensusDpos::_internal_add_dynasty() {
  return dynasty_.Add();
}
inline void GenesisConsensusDpos::add_dynasty(const std::string& value) {
  dynasty_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:corepb.GenesisConsensusDpos.dynasty)
}
inline void GenesisConsensusDpos::add_dynasty(std::string&& value) {
  dynasty_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:corepb.GenesisConsensusDpos.dynasty)
}
inline void GenesisConsensusDpos::add_dynasty(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  dynasty_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:corepb.GenesisConsensusDpos.dynasty)
}
inline void GenesisConsensusDpos::add_dynasty(const char* value, size_t size) {
  dynasty_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:corepb.GenesisConsensusDpos.dynasty)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GenesisConsensusDpos::dynasty() const {
  // @@protoc_insertion_point(field_list:corepb.GenesisConsensusDpos.dynasty)
  return dynasty_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GenesisConsensusDpos::mutable_dynasty() {
  // @@protoc_insertion_point(field_mutable_list:corepb.GenesisConsensusDpos.dynasty)
  return &dynasty_;
}

// -------------------------------------------------------------------

// GenesisTokenDistribution

// string address = 1;
inline void GenesisTokenDistribution::clear_address() {
  address_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& GenesisTokenDistribution::address() const {
  // @@protoc_insertion_point(field_get:corepb.GenesisTokenDistribution.address)
  return _internal_address();
}
inline void GenesisTokenDistribution::set_address(const std::string& value) {
  _internal_set_address(value);
  // @@protoc_insertion_point(field_set:corepb.GenesisTokenDistribution.address)
}
inline std::string* GenesisTokenDistribution::mutable_address() {
  // @@protoc_insertion_point(field_mutable:corepb.GenesisTokenDistribution.address)
  return _internal_mutable_address();
}
inline const std::string& GenesisTokenDistribution::_internal_address() const {
  return address_.GetNoArena();
}
inline void GenesisTokenDistribution::_internal_set_address(const std::string& value) {
  
  address_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void GenesisTokenDistribution::set_address(std::string&& value) {
  
  address_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:corepb.GenesisTokenDistribution.address)
}
inline void GenesisTokenDistribution::set_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  address_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:corepb.GenesisTokenDistribution.address)
}
inline void GenesisTokenDistribution::set_address(const char* value, size_t size) {
  
  address_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:corepb.GenesisTokenDistribution.address)
}
inline std::string* GenesisTokenDistribution::_internal_mutable_address() {
  
  return address_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* GenesisTokenDistribution::release_address() {
  // @@protoc_insertion_point(field_release:corepb.GenesisTokenDistribution.address)
  
  return address_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void GenesisTokenDistribution::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    
  } else {
    
  }
  address_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:corepb.GenesisTokenDistribution.address)
}

// string value = 2;
inline void GenesisTokenDistribution::clear_value() {
  value_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& GenesisTokenDistribution::value() const {
  // @@protoc_insertion_point(field_get:corepb.GenesisTokenDistribution.value)
  return _internal_value();
}
inline void GenesisTokenDistribution::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:corepb.GenesisTokenDistribution.value)
}
inline std::string* GenesisTokenDistribution::mutable_value() {
  // @@protoc_insertion_point(field_mutable:corepb.GenesisTokenDistribution.value)
  return _internal_mutable_value();
}
inline const std::string& GenesisTokenDistribution::_internal_value() const {
  return value_.GetNoArena();
}
inline void GenesisTokenDistribution::_internal_set_value(const std::string& value) {
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void GenesisTokenDistribution::set_value(std::string&& value) {
  
  value_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:corepb.GenesisTokenDistribution.value)
}
inline void GenesisTokenDistribution::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:corepb.GenesisTokenDistribution.value)
}
inline void GenesisTokenDistribution::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:corepb.GenesisTokenDistribution.value)
}
inline std::string* GenesisTokenDistribution::_internal_mutable_value() {
  
  return value_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* GenesisTokenDistribution::release_value() {
  // @@protoc_insertion_point(field_release:corepb.GenesisTokenDistribution.value)
  
  return value_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void GenesisTokenDistribution::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:corepb.GenesisTokenDistribution.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace corepb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_genesis_2eproto
